AllCops:
  Exclude:
    - 'bin/*'
    - 'config/boot.rb'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

# Mongoid doesn't support has_many :through
Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/Lambda:
  Enabled: false

Metrics/LineLength:
  Max: 100
